In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
import pandas as pd

# Try different encodings if the first one doesn't work
try:
    football = pd.read_csv(r'C:\Users\USER\OneDrive\CB\ALX\Data Science\Integrated Exams\Exam_Part_I_data\Exam_Part_I_data 5\football_players.csv', encoding='latin1')
except UnicodeDecodeError:
    football = pd.read_csv(r'C:\Users\USER\OneDrive\CB\ALX\Data Science\Integrated Exams\Exam_Part_I_data\Exam_Part_I_data 5\football_players.csv', encoding='ISO-8859-1')

# Display the first few rows of the DataFrame
football.head()

,Name,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,...,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions,Preferred Positions Type
0,Cristiano Ronaldo,32,Portugal,94.0,89.0,63.0,89.0,63.0,93.0,95.0,...,94.0,23.0,91.0,92.0,31.0,80.0,85.0,88.0,ST LW,Forward
1,L. Messi,30,Argentina,93.0,92.0,48.0,90.0,95.0,95.0,96.0,...,85.0,26.0,87.0,73.0,28.0,59.0,90.0,85.0,RW,Forward
2,Neymar,25,Brazil,92.0,94.0,56.0,96.0,82.0,95.0,92.0,...,80.0,33.0,90.0,78.0,24.0,53.0,80.0,83.0,LW,Forward
3,L. Suárez,30,Uruguay,92.0,88.0,78.0,86.0,60.0,91.0,83.0,...,87.0,38.0,77.0,89.0,45.0,80.0,84.0,88.0,ST,Forward
4,M. Neuer,31,Germany,92.0,58.0,29.0,52.0,35.0,48.0,70.0,...,25.0,11.0,61.0,44.0,10.0,83.0,70.0,11.0,GK,GoalKeeper

In [7]:
football.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 40 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      17981 non-null  object
 1   Age                       17981 non-null  int64
 2   Nationality               17981 non-null  object
 3   Overall                   17981 non-null  float64
 4   Acceleration              17981 non-null  float64
 5   Aggression                17981 non-null  float64
 6   Agility                   17981 non-null  float64
 7   Balance                   17981 non-null  float64
 8   Ball control              17981 non-null  float64
 9   Composure                 17981 non-null  float64
 10  Crossing                  17981 non-null  float64
 11  Curve                     17981 non-null  float64
 12  Dribbling                 17981 non-null  float64
 13  Finishing                 17981 non-null  float64
 14  Free kick accuracy        17981 non-null  float64
 15  GK diving                 17981 non-null  float64
 16  GK handling               17981 non-null  float64
 17  GK kicking                17981 non-null  float64
 18  GK positioning            17981 non-null  float64
 19  GK reflexes               17981 non-null  float64
 20  Heading accuracy          17981 non-null  float64
 21  Interceptions             17981 non-null  float64
 22  Jumping                   17981 non-null  float64
 23  Long passing              17981 non-null  float64
 24  Long shots                17981 non-null  float64
 25  Marking                   17981 non-null  float64
 26  Penalties                 17981 non-null  float64
 27  Positioning               17981 non-null  float64
 28  Reactions                 17981 non-null  float64
 29  Short passing             17981 non-null  float64
 30  Shot power                17981 non-null  float64
 31  Sliding tackle            17981 non-null  float64
 32  Sprint speed              17981 non-null  float64
 33  Stamina                   17981 non-null  float64
 34  Standing tackle           17981 non-null  float64
 35  Strength                  17981 non-null  float64
 36  Vision                    17981 non-null  float64
 37  Volleys                   17981 non-null  float64
 38  Preferred Positions       17981 non-null  object
 39  Preferred Positions Type  17981 non-null  object
dtypes: float64(35), int64(1), object(4)
memory usage: 5.5+ MB

#### 35
How would you add a row of entries 92, 88 and 78 to a 2-D numpy array a with dimensions of 3x3? (1 mark)

In [13]:
a = range(9)
a_array = np.array(a).reshape((3,3))

In [17]:
a_array
np.append(a_array, [[92, 88, 78]], axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [92, 88, 78]])

In [23]:
football.iloc[4]

Name                          M. Neuer
Age                                 31
Nationality                    Germany
Overall                           92.0
Acceleration                      58.0
Aggression                        29.0
Agility                           52.0
Balance                           35.0
Ball control                      48.0
Composure                         70.0
Crossing                          15.0
Curve                             14.0
Dribbling                         30.0
Finishing                         13.0
Free kick accuracy                11.0
GK diving                         91.0
GK handling                       90.0
GK kicking                        95.0
GK positioning                    91.0
GK reflexes                       89.0
Heading accuracy                  25.0
Interceptions                     30.0
Jumping                           78.0
Long passing                      59.0
Long shots                        16.0
Marking                           10.0
Penalties                         47.0
Positioning                       12.0
Reactions                         85.0
Short passing                     55.0
Shot power                        25.0
Sliding tackle                    11.0
Sprint speed                      61.0
Stamina                           44.0
Standing tackle                   10.0
Strength                          83.0
Vision                            70.0
Volleys                           11.0
Preferred Positions                GK
Preferred Positions Type    GoalKeeper
Name: 4, dtype: object

#### Question 38
Which Algeria player had the highest overall rating?

In [29]:


football[football['Nationality'] == 'Algeria'].sort_values(by= 'Overall', ascending= False).head(1)

,Name,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,...,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions,Preferred Positions Type
143,R. Mahrez,26,Algeria,83.0,85.0,40.0,92.0,85.0,88.0,82.0,...,76.0,19.0,80.0,75.0,23.0,51.0,79.0,71.0,RM,Midfielder

In [32]:
football[football['Preferred Positions Type'] == 'Back'].sort_values(by = 'Sliding tackle', ascending= False)

,Name,Age,Nationality,Overall,Acceleration,Aggression,Agility,Balance,Ball control,Composure,...,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,Preferred Positions,Preferred Positions Type
10,Sergio Ramos,31,Spain,90.0,75.0,84.0,79.0,60.0,84.0,80.0,...,79.0,91.0,77.0,84.0,89.0,81.0,63.0,66.0,CB,Back
25,J. Boateng,28,Germany,88.0,72.0,82.0,58.0,53.0,71.0,86.0,...,79.0,90.0,78.0,74.0,91.0,91.0,76.0,53.0,CB,Back
27,M. Hummels,28,Germany,88.0,62.0,66.0,64.0,58.0,77.0,91.0,...,71.0,90.0,65.0,66.0,92.0,85.0,79.0,60.0,CB,Back
17,G. Chiellini,32,Italy,89.0,68.0,92.0,59.0,64.0,57.0,82.0,...,78.0,90.0,78.0,68.0,92.0,91.0,50.0,45.0,CB,Back
26,D. Godín,31,Uruguay,88.0,62.0,86.0,63.0,58.0,76.0,82.0,...,67.0,89.0,67.0,67.0,86.0,80.0,52.0,47.0,CB,Back
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9101,M. Konczkowski,23,Poland,66.0,74.0,61.0,71.0,72.0,62.0,63.0,...,34.0,22.0,83.0,83.0,63.0,56.0,21.0,25.0,RB,Back
11165,T. Aoki,34,Japan,64.0,43.0,61.0,58.0,56.0,22.0,23.0,...,20.0,22.0,48.0,50.0,23.0,65.0,56.0,51.0,CB,Back
11742,L. O'Neill,25,England,64.0,76.0,58.0,68.0,63.0,61.0,44.0,...,57.0,22.0,73.0,72.0,23.0,71.0,50.0,43.0,RM RWB RB,Back
11767,D. Leadbitter,26,England,64.0,89.0,54.0,79.0,53.0,55.0,48.0,...,39.0,21.0,90.0,77.0,61.0,68.0,42.0,29.0,RWB RB,Back
17863,R. Woodcock,18,Scotland,50.0,68.0,52.0,56.0,65.0,33.0,48.0,...,29.0,18.0,69.0,21.0,53.0,51.0,42.0,23.0,LB RB,Back

#### Question 40
Which preferred position type of England has on average the highest overall rating? (2 marks)

In [35]:
football[football['Nationality'] == 'England'].groupby('Preferred Positions Type').agg(avg = ('Overall', 'mean')).sort_values(by = 'avg', ascending= False)

                                avg
Preferred Positions Type
Back                      63.669104
Midfielder                63.393035
Forward                   62.513245
GoalKeeper                61.078652

#### Question 41
Brazil’s forwards have a higher average overall rating than the backs (1 mark)

In [36]:
football[football['Nationality'] == 'Brazil'].groupby('Preferred Positions Type').agg(avg = ('Overall', 'mean')).sort_values(by = 'avg', ascending= False)

                                avg
Preferred Positions Type
GoalKeeper                71.611940
Back                      71.490975
Midfielder                70.681356
Forward                   70.028902

#### Question 42
Which country has the oldest player? (2 marks)

In [39]:
football[['Nationality', 'Age', 'Name', 'Preferred Positions Type']].sort_values(by = 'Age', ascending= False)

       Nationality  Age           Name Preferred Positions Type
17977      England   47  B. Richardson               GoalKeeper
5314         Egypt   44   E. El Hadary               GoalKeeper
4839        Mexico   44       O. Pérez               GoalKeeper
16834      England   43      J. Walker               GoalKeeper
16696        Wales   43       D. Coyne               GoalKeeper
...            ...  ...            ...                      ...
13733        Italy   16     E. Vignato               Midfielder
15119  Netherlands   16  L. Geertruida                     Back
16116      Germany   16      M. Sprang               GoalKeeper
17014      Romania   16    R. Strechie               Midfielder
10556  Netherlands   16      K. Pierie                     Back

[17981 rows x 4 columns]

#### Question 43
Which of the following attributes is on average the lowest for goalkeepers? (3 marks)

In [44]:
football[football['Preferred Positions Type'] == 'GoalKeeper'][['GK diving','GK handling', 'GK reflexes', 'GK kicking']].mean().sort_values(ascending= False)

GK reflexes    63.848887
GK diving      62.988157
GK handling    60.675983
GK kicking     59.424443
dtype: float64

#### Question 44
Which preferred positions type has the most entries in this dataset? (3 marks)

In [47]:
football.groupby('Preferred Positions Type').agg(n = ('Preferred Positions Type','count')).sort_values(by = 'n', ascending= False)

                             n
Preferred Positions Type
Midfielder                6769
Back                      5848
Forward                   3253
GoalKeeper                2111

#### Question 45 
Which player from Portugal, that is younger than 25, has the highest overall rating? (3 marks)

In [48]:
football[(football['Nationality'] == 'Portugal') & (football['Age'] < 25)][['Name', 'Age', 'Nationality', 'Overall']].sort_values(by= 'Overall', ascending= False)

                 Name  Age Nationality  Overall
94     Bernardo Silva   22    Portugal     84.0
133        João Mário   24    Portugal     83.0
209       André Gomes   23    Portugal     82.0
300     Nélson Semedo   23    Portugal     81.0
301    Gelson Martins   22    Portugal     81.0
...               ...  ...         ...      ...
15577      Toni Gomes   18    Portugal     58.0
16526   Pedro Pacheco   20    Portugal     56.0
16717    Herson Alves   20    Portugal     55.0
16987        E. Sousa   22    Portugal     54.0
17143       Dany Mota   19    Portugal     54.0

[178 rows x 4 columns]